jwt:
  secret: Wilson93905473*

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
    address: 192.168.40.108

spring:
  datasource:
    url: jdbc:mysql://junction.proxy.rlwy.net:16710/railway?serverTimezone=UTC
    username: root
    password: sCceTNlTjVRnjDDlAOIezjvyoKroPljK
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: springtech258@gmail.com
    password: zwdl ncio vgjo smeh
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

app:
  base-url: https://projet-erp-frontend.vercel.app
